### ISSUE TITLE
bug: empty values shouldn't be send

### ISSUE THREAD

**Issue by Miyli** [myth-MC/social#14]
I want to disable the message when joining/entering a channel so I changed the line into [] or ''.

Putting [] seems to error the plugin and '' simply prints a blank line. This also includes things such as the icon value or divider.

**Comment by U8092** [comment]
Hey, @Miyli!

Branch `dev/0.3.1` now includes a fix for this. Messages and text fields can now be 'disabled' by using '' as you described. For example:
```yaml
# Command messages
commands:
  channelChanged: ''
  ...
``` 


There's also a release candidate build available in our [Discord server](https://discord.gg/bpkwdzREcR) in case you want to check it out! 🙂
